# DEVELOPMENT
FROM node:24.0.0-alpine AS development
WORKDIR /fyprojectfe
COPY package*.json ./
RUN npm ci
COPY . .
CMD ["npm", "start"]


# PRODUCTION BUILD
FROM node:24.0.0-alpine AS build
WORKDIR /fyprojectfe
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


# PRODUCTION SERVE
FROM nginx:alpine AS production
COPY --from=build /fyprojectfe/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
