# DEVELOPEMENT
FROM node:24.0.0-alpine AS development
WORKDIR /fyprojectbe
COPY package*.json ./
RUN npm ci --omit=dev 
COPY . .
CMD ["npm", "run","devStart"]

# PRODUCTION
FROM node:24.0.0-alpine AS production
WORKDIR /fyprojectbe
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
CMD ["node", "server.js"]